# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='types.proto',
  package='lattice',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0btypes.proto\x12\x07lattice\"G\n\x04\x41tom\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0e\n\x06radius\x18\x04 \x01(\x02\x12\x0e\n\x06symbol\x18\x05 \x01(\t\"\x84\x01\n\x07Lattice\x12\x1c\n\x05\x61toms\x18\x01 \x03(\x0b\x32\r.lattice.Atom\x12,\n\x06\x63olors\x18\x02 \x03(\x0b\x32\x1c.lattice.Lattice.ColorsEntry\x1a-\n\x0b\x43olorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')
)




_ATOM = _descriptor.Descriptor(
  name='Atom',
  full_name='lattice.Atom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='lattice.Atom.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='lattice.Atom.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='lattice.Atom.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radius', full_name='lattice.Atom.radius', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='lattice.Atom.symbol', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=95,
)


_LATTICE_COLORSENTRY = _descriptor.Descriptor(
  name='ColorsEntry',
  full_name='lattice.Lattice.ColorsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='lattice.Lattice.ColorsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='lattice.Lattice.ColorsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=230,
)

_LATTICE = _descriptor.Descriptor(
  name='Lattice',
  full_name='lattice.Lattice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='atoms', full_name='lattice.Lattice.atoms', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='colors', full_name='lattice.Lattice.colors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LATTICE_COLORSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=230,
)

_LATTICE_COLORSENTRY.containing_type = _LATTICE
_LATTICE.fields_by_name['atoms'].message_type = _ATOM
_LATTICE.fields_by_name['colors'].message_type = _LATTICE_COLORSENTRY
DESCRIPTOR.message_types_by_name['Atom'] = _ATOM
DESCRIPTOR.message_types_by_name['Lattice'] = _LATTICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Atom = _reflection.GeneratedProtocolMessageType('Atom', (_message.Message,), dict(
  DESCRIPTOR = _ATOM,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:lattice.Atom)
  ))
_sym_db.RegisterMessage(Atom)

Lattice = _reflection.GeneratedProtocolMessageType('Lattice', (_message.Message,), dict(

  ColorsEntry = _reflection.GeneratedProtocolMessageType('ColorsEntry', (_message.Message,), dict(
    DESCRIPTOR = _LATTICE_COLORSENTRY,
    __module__ = 'types_pb2'
    # @@protoc_insertion_point(class_scope:lattice.Lattice.ColorsEntry)
    ))
  ,
  DESCRIPTOR = _LATTICE,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:lattice.Lattice)
  ))
_sym_db.RegisterMessage(Lattice)
_sym_db.RegisterMessage(Lattice.ColorsEntry)


_LATTICE_COLORSENTRY._options = None
# @@protoc_insertion_point(module_scope)
