// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package lattice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Atom struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Radius               float32  `protobuf:"fixed32,4,opt,name=radius,proto3" json:"radius,omitempty"`
	Symbol               string   `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Atom) Reset()         { *m = Atom{} }
func (m *Atom) String() string { return proto.CompactTextString(m) }
func (*Atom) ProtoMessage()    {}
func (*Atom) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *Atom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Atom.Unmarshal(m, b)
}
func (m *Atom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Atom.Marshal(b, m, deterministic)
}
func (m *Atom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Atom.Merge(m, src)
}
func (m *Atom) XXX_Size() int {
	return xxx_messageInfo_Atom.Size(m)
}
func (m *Atom) XXX_DiscardUnknown() {
	xxx_messageInfo_Atom.DiscardUnknown(m)
}

var xxx_messageInfo_Atom proto.InternalMessageInfo

func (m *Atom) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Atom) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Atom) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *Atom) GetRadius() float32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *Atom) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type Lattice struct {
	Atoms                []*Atom           `protobuf:"bytes,1,rep,name=atoms,proto3" json:"atoms,omitempty"`
	Colors               map[string]string `protobuf:"bytes,2,rep,name=colors,proto3" json:"colors,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Lattice) Reset()         { *m = Lattice{} }
func (m *Lattice) String() string { return proto.CompactTextString(m) }
func (*Lattice) ProtoMessage()    {}
func (*Lattice) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *Lattice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lattice.Unmarshal(m, b)
}
func (m *Lattice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lattice.Marshal(b, m, deterministic)
}
func (m *Lattice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lattice.Merge(m, src)
}
func (m *Lattice) XXX_Size() int {
	return xxx_messageInfo_Lattice.Size(m)
}
func (m *Lattice) XXX_DiscardUnknown() {
	xxx_messageInfo_Lattice.DiscardUnknown(m)
}

var xxx_messageInfo_Lattice proto.InternalMessageInfo

func (m *Lattice) GetAtoms() []*Atom {
	if m != nil {
		return m.Atoms
	}
	return nil
}

func (m *Lattice) GetColors() map[string]string {
	if m != nil {
		return m.Colors
	}
	return nil
}

func init() {
	proto.RegisterType((*Atom)(nil), "lattice.Atom")
	proto.RegisterType((*Lattice)(nil), "lattice.Lattice")
	proto.RegisterMapType((map[string]string)(nil), "lattice.Lattice.ColorsEntry")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x18, 0xc4, 0xf9, 0xd2, 0x6d, 0x97, 0x7e, 0x55, 0x90, 0x20, 0x12, 0xc4, 0x43, 0x59, 0x2f, 0x3d,
	0xe5, 0xa0, 0x1e, 0xd4, 0x9b, 0x88, 0x37, 0x4f, 0x79, 0x02, 0xb3, 0x6b, 0x0e, 0x8b, 0xa9, 0x29,
	0x49, 0x2a, 0x4d, 0x5f, 0xc6, 0x57, 0x95, 0xfc, 0x41, 0xf6, 0x96, 0xdf, 0xcc, 0x90, 0xcc, 0x04,
	0x3b, 0x1f, 0x26, 0xe5, 0xf8, 0x64, 0x8d, 0x37, 0x74, 0xab, 0xa5, 0xf7, 0xc7, 0x83, 0xda, 0x7d,
	0xe0, 0xe6, 0xc5, 0x9b, 0x91, 0x9e, 0x21, 0x2c, 0x0c, 0x7a, 0x18, 0x88, 0x80, 0x25, 0x52, 0x60,
	0x24, 0x53, 0x88, 0xb4, 0xb2, 0x2a, 0xd3, 0x4a, 0xaf, 0xb0, 0xb1, 0xf2, 0xf3, 0x38, 0x3b, 0xb6,
	0x49, 0x52, 0xa1, 0xa8, 0xbb, 0x30, 0xee, 0x8d, 0x66, 0x75, 0x0f, 0x43, 0x2b, 0x0a, 0xed, 0x7e,
	0x01, 0xb7, 0xef, 0xf9, 0x35, 0x7a, 0x8b, 0xb5, 0xf4, 0x66, 0x74, 0x0c, 0xfa, 0x6a, 0xe8, 0xee,
	0xce, 0x79, 0xa9, 0xc1, 0x63, 0x07, 0x91, 0x3d, 0xfa, 0x80, 0xcd, 0xc1, 0x68, 0x63, 0x1d, 0x23,
	0x29, 0x75, 0xf3, 0x9f, 0x2a, 0xd7, 0xf0, 0xd7, 0x64, 0xbf, 0x7d, 0x7b, 0x1b, 0x44, 0xc9, 0x5e,
	0x3f, 0x61, 0x77, 0x22, 0xd3, 0x0b, 0xac, 0xbe, 0x54, 0x48, 0x8b, 0x5a, 0x11, 0x8f, 0xf4, 0x12,
	0xeb, 0x1f, 0xa9, 0x67, 0x95, 0x76, 0xb5, 0x22, 0xc3, 0x33, 0x79, 0x84, 0x7d, 0x93, 0xfe, 0xe4,
	0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xdf, 0x4d, 0x67, 0x22, 0x01, 0x00, 0x00,
}
