// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package lattice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtoAtom struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float32  `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Radius               float32  `protobuf:"fixed32,4,opt,name=radius,proto3" json:"radius,omitempty"`
	Symbol               string   `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtoAtom) Reset()         { *m = ProtoAtom{} }
func (m *ProtoAtom) String() string { return proto.CompactTextString(m) }
func (*ProtoAtom) ProtoMessage()    {}
func (*ProtoAtom) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *ProtoAtom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoAtom.Unmarshal(m, b)
}
func (m *ProtoAtom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoAtom.Marshal(b, m, deterministic)
}
func (m *ProtoAtom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoAtom.Merge(m, src)
}
func (m *ProtoAtom) XXX_Size() int {
	return xxx_messageInfo_ProtoAtom.Size(m)
}
func (m *ProtoAtom) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoAtom.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoAtom proto.InternalMessageInfo

func (m *ProtoAtom) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ProtoAtom) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *ProtoAtom) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *ProtoAtom) GetRadius() float32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *ProtoAtom) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type ProtoLattice struct {
	Atoms                []*ProtoAtom `protobuf:"bytes,1,rep,name=atoms,proto3" json:"atoms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProtoLattice) Reset()         { *m = ProtoLattice{} }
func (m *ProtoLattice) String() string { return proto.CompactTextString(m) }
func (*ProtoLattice) ProtoMessage()    {}
func (*ProtoLattice) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *ProtoLattice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtoLattice.Unmarshal(m, b)
}
func (m *ProtoLattice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtoLattice.Marshal(b, m, deterministic)
}
func (m *ProtoLattice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtoLattice.Merge(m, src)
}
func (m *ProtoLattice) XXX_Size() int {
	return xxx_messageInfo_ProtoLattice.Size(m)
}
func (m *ProtoLattice) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtoLattice.DiscardUnknown(m)
}

var xxx_messageInfo_ProtoLattice proto.InternalMessageInfo

func (m *ProtoLattice) GetAtoms() []*ProtoAtom {
	if m != nil {
		return m.Atoms
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoAtom)(nil), "lattice.ProtoAtom")
	proto.RegisterType((*ProtoLattice)(nil), "lattice.ProtoLattice")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x49, 0x2c, 0x29, 0xc9, 0x4c, 0x4e,
	0x55, 0x4a, 0xe5, 0xe2, 0x0c, 0x00, 0x89, 0x38, 0x96, 0xe4, 0xe7, 0x0a, 0xf1, 0x70, 0x31, 0x56,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x05, 0x31, 0x56, 0x80, 0x78, 0x95, 0x12, 0x4c, 0x10, 0x5e,
	0x25, 0x88, 0x57, 0x25, 0xc1, 0x0c, 0xe1, 0x55, 0x09, 0x89, 0x71, 0xb1, 0x15, 0x25, 0xa6, 0x64,
	0x96, 0x16, 0x4b, 0xb0, 0x80, 0x85, 0xa0, 0x3c, 0x90, 0x78, 0x71, 0x65, 0x6e, 0x52, 0x7e, 0x8e,
	0x04, 0xab, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x94, 0xa7, 0x64, 0xc1, 0xc5, 0x03, 0xb6, 0xc6, 0x07,
	0x62, 0xad, 0x90, 0x06, 0x17, 0x6b, 0x62, 0x49, 0x7e, 0x6e, 0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06,
	0xb7, 0x91, 0x90, 0x1e, 0xd4, 0x3d, 0x7a, 0x70, 0xc7, 0x04, 0x41, 0x14, 0x24, 0xb1, 0x81, 0x1d,
	0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xad, 0x0f, 0x6f, 0x91, 0xbf, 0x00, 0x00, 0x00,
}
